
import classes.mainclass;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshat
 */
public class customer_bill extends javax.swing.JFrame {
    String[] filename = {"spiderman.jpg","dunkirk.jpeg","baby.jpg","wonderwoman.jpg","logan.jpg","annabelle.jpg","Dangal.jpg","Bahubali.jpg"};
    ImageIcon[] images;

    /**
     * Creates new form customer_bill
     */
    public customer_bill() {
        super("BILL");
        initComponents();
        
        images = new ImageIcon[filename.length];
        Integer[] intArray = new Integer[filename.length];
        for (int i = 0; i < filename.length; i++) {
            intArray[i] = i;
            images[i] = createImageIcon("Images/" + filename[i]);
            if (images[i] != null) {
                images[i].setDescription(filename[i]);
            }
        }
        
        float gst = 0;
        
        
        gst = ( 18 * mainclass.cost ) / 100;
        mainclass.totAmount = mainclass.cost + gst ;
        
        DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date1 = new java.util.Date();
        String id = dateFormat1.format(date1);
        
        lbcustname.setText(mainclass.custName);
        lbbid.setText(mainclass.ticketID);
        lbmoviename.setText(mainclass.selected_movie);
        lbtime.setText(mainclass.time_booked);
        lbdate.setText(id);
        lbticketcount.setText(mainclass.finalTicketCount);
        lbscreen.setText(mainclass.final_screen_no);
        lbsno.setText(mainclass.ticketSeatNo);
        lbcost.setText("Rs. " +mainclass.cost + ".00");
        lbgst.setText("Rs. " + gst +"0");
        lbamt.setText("Rs. " + mainclass.totAmount + "0");
        
        
        if(mainclass.selected_movie == "Spiderman")
        {
            images[0] = createImageIcon("Images/" + filename[0]);
            pic.setIcon(images[0]);
        }
        
        else if(mainclass.selected_movie == "Dunkirk")
        {
            images[1] = createImageIcon("Images/" + filename[1]);
            pic.setIcon(images[1]);
        }
        
        else if(mainclass.selected_movie == "Baby Driver")
        {
            images[2] = createImageIcon("Images/" + filename[2]);
            pic.setIcon(images[2]);
        }
        
        else if(mainclass.selected_movie == "Wonderwoman")
        {
            images[3] = createImageIcon("Images/" + filename[3]);
            pic.setIcon(images[3]);
        }
        
        else if(mainclass.selected_movie == "Logan")
        {
            images[4] = createImageIcon("Images/" + filename[4]);
            pic.setIcon(images[4]);
        }
        
        else if(mainclass.selected_movie == "Annabelle")
        {
            images[5] = createImageIcon("Images/" + filename[5]);
            pic.setIcon(images[5]);
        }
        
        else if(mainclass.selected_movie == "Dangal")
        {
            images[6] = createImageIcon("Images/" + filename[6]);
            pic.setIcon(images[6]);
        }
        
        else if(mainclass.selected_movie == "Baahubali")
        {
            images[7] = createImageIcon("Images/" + filename[7]);
            pic.setIcon(images[7]);
        }
        
        mainclass.smsSend = ""+mainclass.custName+":Your%20booking%20is%20confirmed%20with%20ticket%20ID%20="+mainclass.ticketID+"%20.Kindly%20show%20this%20ID%20at%20booking%20counter%20in%20an%20hour%20with%20amount=Rs."+mainclass.totAmount+"%20.Thanks!";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbbid = new javax.swing.JLabel();
        lbmoviename = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbticketcount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbscreen = new javax.swing.JLabel();
        lbsno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbcost = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbgst = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbamt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbcustname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 86, 350, 518));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("YOUR BOOKING IS CONFIRMED !");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 29, -1, 39));

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("BOOKING ID:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 136, -1, -1));

        lbbid.setBackground(new java.awt.Color(153, 204, 255));
        lbbid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbbid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbbid.setOpaque(true);
        getContentPane().add(lbbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 139, 99, 14));

        lbmoviename.setBackground(new java.awt.Color(153, 204, 255));
        lbmoviename.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        lbmoviename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbmoviename.setText(" ");
        lbmoviename.setOpaque(true);
        getContentPane().add(lbmoviename, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 186, 294, -1));

        lbtime.setBackground(new java.awt.Color(153, 204, 255));
        lbtime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbtime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbtime.setOpaque(true);
        getContentPane().add(lbtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 255, 82, 33));

        lbdate.setBackground(new java.awt.Color(153, 204, 255));
        lbdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdate.setOpaque(true);
        getContentPane().add(lbdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 255, 141, 33));

        lbticketcount.setBackground(new java.awt.Color(153, 204, 255));
        lbticketcount.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbticketcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbticketcount.setOpaque(true);
        getContentPane().add(lbticketcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 352, 50, 50));

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tickets");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 408, 50, -1));

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("SCREEN:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 321, -1, 25));

        lbscreen.setBackground(new java.awt.Color(153, 204, 255));
        lbscreen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbscreen.setOpaque(true);
        getContentPane().add(lbscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 321, 50, 25));

        lbsno.setBackground(new java.awt.Color(153, 204, 255));
        lbsno.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbsno.setOpaque(true);
        getContentPane().add(lbsno, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 352, 204, 50));

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("TICKET COST");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 478, -1, -1));

        lbcost.setBackground(new java.awt.Color(153, 204, 255));
        lbcost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbcost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbcost.setOpaque(true);
        getContentPane().add(lbcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 478, 70, 14));

        jLabel7.setBackground(new java.awt.Color(153, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Integrated GST (IGST) @ 18.00%");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 526, -1, -1));

        lbgst.setBackground(new java.awt.Color(153, 204, 255));
        lbgst.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbgst.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbgst.setOpaque(true);
        getContentPane().add(lbgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 526, 70, 14));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("TOTAL AMOUNT");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 574, -1, -1));

        lbamt.setBackground(new java.awt.Color(153, 204, 255));
        lbamt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbamt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbamt.setOpaque(true);
        getContentPane().add(lbamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 574, 70, 14));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 639, 125, 43));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setText("MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 639, 125, 43));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("CUSTOMER NAME:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 86, -1, -1));

        lbcustname.setBackground(new java.awt.Color(153, 204, 255));
        lbcustname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbcustname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbcustname.setOpaque(true);
        getContentPane().add(lbcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 86, 99, 14));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back_lights.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       mainclass.selected_movie = "";
       mainclass.time_booked = "";
       mainclass.final_screen_no = "";
       mainclass.finalTicketCount = "";
       mainclass.custName = "";
       mainclass.custPh = "";
       mainclass.ticketID = "";
       mainclass.date = "";
       mainclass.ticketSeatNo = "";
       mainclass.sid  = 0;
       mainclass.cost = 0;
       mainclass.timeInt = 0;
       mainclass.totAmount = 0;
       mainclass.smsRecvd = "";
       mainclass.smsSend = "";
       mainclass.bookingMode = "";
        
       new menu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainclass.selected_movie = "";
       mainclass.time_booked = "";
       mainclass.final_screen_no = "";
       mainclass.finalTicketCount = "";
       mainclass.custName = "";
       mainclass.custPh = "";
       mainclass.ticketID = "";
       mainclass.date = "";
       mainclass.ticketSeatNo = "";
       mainclass.sid  = 0;
       mainclass.cost = 0;
       mainclass.timeInt = 0;
       mainclass.totAmount = 0;
       mainclass.smsRecvd = "";
       mainclass.smsSend = "";
       mainclass.bookingMode = "";
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbamt;
    private javax.swing.JLabel lbbid;
    private javax.swing.JLabel lbcost;
    private javax.swing.JLabel lbcustname;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbgst;
    private javax.swing.JLabel lbmoviename;
    private javax.swing.JLabel lbscreen;
    private javax.swing.JLabel lbsno;
    private javax.swing.JLabel lbticketcount;
    private javax.swing.JLabel lbtime;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables

    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = movie_select.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
                return null;
        }
    }
    
}
