/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import classes.mainclass;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Akshat
 */
public class sms_send extends javax.swing.JFrame {
   String[] filename = {"spiderman.jpg","dunkirk.jpeg","baby.jpg","wonderwoman.jpg","logan.jpg","annabelle.jpg","Dangal.jpg","Bahubali.jpg"};
   ImageIcon[] images;
    
    // JDBC driver name and database URL
   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String DB_URL = "jdbc:mysql://localhost/movies";

   //  Database credentials
   static final String USER = "root";
   static final String PASS = "goodluck";
    
    /**
     * Creates new form sms_send
     */
    public sms_send() {
        super("SMS SENDING");
        initComponents();
        
        images = new ImageIcon[filename.length];
        Integer[] intArray = new Integer[filename.length];
        for (int i = 0; i < filename.length; i++) {
            intArray[i] = i;
            images[i] = createImageIcon("Images/" + filename[i]);
            if (images[i] != null) {
                images[i].setDescription(filename[i]);
            }
        }
        btexit.setVisible(false);
        btmm.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        lbamt.setVisible(false);
        lbbid.setVisible(false);
        lbcost.setVisible(false);
        lbcustname.setVisible(false);
        lbdate.setVisible(false);
        lbgst.setVisible(false);
        lbmoviename.setVisible(false);
        lbphone.setVisible(false);
        lbscreen.setVisible(false);
        lbsno.setVisible(false);
        lbticketcount.setVisible(false);
        lbtime.setVisible(false);
        pic.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbscreen = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        lbsno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbcost = new javax.swing.JLabel();
        lbbid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbmoviename = new javax.swing.JLabel();
        lbgst = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbamt = new javax.swing.JLabel();
        lbticketcount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbcustname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbphone = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        btmm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMS RESPONSE");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 30));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("ENTER TICKET ID:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 52, -1, -1));
        getContentPane().add(txttid, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 49, 110, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 48, 57, -1));

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("SCREEN:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 416, -1, 25));

        lbscreen.setBackground(new java.awt.Color(153, 204, 255));
        lbscreen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbscreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbscreen.setOpaque(true);
        getContentPane().add(lbscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 416, 50, 25));
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 131, 350, 518));

        lbsno.setBackground(new java.awt.Color(153, 204, 255));
        lbsno.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbsno.setOpaque(true);
        getContentPane().add(lbsno, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 447, 284, 50));

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("TICKET COST");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 573, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("BOOKING ID:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 231, -1, -1));

        lbcost.setBackground(new java.awt.Color(153, 204, 255));
        lbcost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbcost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbcost.setOpaque(true);
        getContentPane().add(lbcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 576, 70, 14));

        lbbid.setBackground(new java.awt.Color(153, 204, 255));
        lbbid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbbid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbbid.setOpaque(true);
        getContentPane().add(lbbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 231, 99, 14));

        jLabel7.setBackground(new java.awt.Color(153, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Integrated GST (IGST) @ 18.00%");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 621, -1, -1));

        lbmoviename.setBackground(new java.awt.Color(153, 204, 255));
        lbmoviename.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        lbmoviename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbmoviename.setText(" ");
        lbmoviename.setOpaque(true);
        getContentPane().add(lbmoviename, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 281, 365, -1));

        lbgst.setBackground(new java.awt.Color(153, 204, 255));
        lbgst.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbgst.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbgst.setOpaque(true);
        getContentPane().add(lbgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 621, 70, 14));

        lbtime.setBackground(new java.awt.Color(153, 204, 255));
        lbtime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbtime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbtime.setOpaque(true);
        getContentPane().add(lbtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 82, 33));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("TOTAL AMOUNT");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 669, -1, -1));

        lbdate.setBackground(new java.awt.Color(153, 204, 255));
        lbdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdate.setOpaque(true);
        getContentPane().add(lbdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 350, 137, 33));

        lbamt.setBackground(new java.awt.Color(153, 204, 255));
        lbamt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbamt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbamt.setOpaque(true);
        getContentPane().add(lbamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 669, 70, 14));

        lbticketcount.setBackground(new java.awt.Color(153, 204, 255));
        lbticketcount.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbticketcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbticketcount.setOpaque(true);
        getContentPane().add(lbticketcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 447, 50, 50));

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tickets");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 503, 50, -1));

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("CUSTOMER NAME:");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 131, -1, -1));

        lbcustname.setBackground(new java.awt.Color(153, 204, 255));
        lbcustname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbcustname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbcustname.setOpaque(true);
        getContentPane().add(lbcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 134, 99, 14));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("CUSTOMER PHONE:");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 181, -1, -1));

        lbphone.setBackground(new java.awt.Color(153, 204, 255));
        lbphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbphone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbphone.setOpaque(true);
        getContentPane().add(lbphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 184, 99, 14));

        btexit.setText("EXIT");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        getContentPane().add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, -1, 42));

        btmm.setText("MAIN MENU");
        btmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmmActionPerformed(evt);
            }
        });
        getContentPane().add(btmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back_lights.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(1386, 780));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        btexit.setVisible(true);
        btmm.setVisible(true);
        String tid  = txttid.getText();
        Connection conn = null;
        Statement stmt = null;
        try{
           //STEP 2: Register JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //STEP 3: Open a connection
           System.out.println("Connecting to a selected database...");
           conn = DriverManager.getConnection(DB_URL, USER, PASS);
           System.out.println("Connected database successfully...");

           //STEP 4: Execute a query
           System.out.println("Creating statement...");
           stmt = conn.createStatement();

           String sql = "SELECT * FROM customer_info ci,cost c WHERE ci.ticket_id='"+tid+"' and c.ticket_id='"+tid+"' and ci.booking_mode='SMS'";
           ResultSet rs = stmt.executeQuery(sql);
           //STEP 5: Extract data from result set
           
           
           while(rs.next()){
              //Retrieve by column name
              System.out.println("HI Result String");
              int cost = rs.getInt("total_cost");
              float gst = 0;
              String mname = rs.getString("movie_name");
              
              jLabel4.setVisible(true);
              jLabel5.setVisible(true);
              jLabel6.setVisible(true);
              jLabel7.setVisible(true);
              jLabel8.setVisible(true);
              jLabel9.setVisible(true);
              lbamt.setVisible(true);
              lbbid.setVisible(true);
              lbcost.setVisible(true);
              lbcustname.setVisible(true);
              lbdate.setVisible(true);
              lbgst.setVisible(true);
              lbmoviename.setVisible(true);
              lbphone.setVisible(true);
              lbscreen.setVisible(true);
              lbsno.setVisible(true);
              lbticketcount.setVisible(true);
              lbtime.setVisible(true);
              pic.setVisible(true);
              jLabel10.setVisible(true);
              jLabel11.setVisible(true);
               
              gst = ( 18 * cost ) / 100;
              mainclass.totAmount = cost + gst ;
        
              lbcustname.setText(rs.getString("name"));
              lbbid.setText(rs.getString("ticket_id"));
              lbmoviename.setText(rs.getString("movie_name"));
              lbtime.setText(rs.getString("time"));
              lbdate.setText(rs.getString("date"));
              lbticketcount.setText(rs.getString("seats_booked"));
              lbscreen.setText(rs.getString("screen_no"));
              lbsno.setText(rs.getString("seat_number"));
              lbcost.setText("Rs. " +rs.getString("total_cost") + ".00");
              lbgst.setText("Rs. " + gst +"0");
              lbamt.setText("Rs. " + mainclass.totAmount + "0");
              lbphone.setText(rs.getString("phone_no"));
              
              System.out.println("MOVIE NAME:"+mname);
              
             if(mname.matches("Spiderman"))
             {
                 images[0] = createImageIcon("Images/" + filename[0]);
                 pic.setIcon(images[0]);
             }

             else if(mname.matches("Dunkirk"))
             {
                 images[1] = createImageIcon("Images/" + filename[1]);
                 pic.setIcon(images[1]);
             }

             else if(mname.matches("Baby Driver"))
             {
                 images[2] = createImageIcon("Images/" + filename[2]);
                 pic.setIcon(images[2]);
             }

             else if(mname.matches("Wonderwoman"))
             {
                 images[3] = createImageIcon("Images/" + filename[3]);
                 pic.setIcon(images[3]);
             }

             else if(mname.matches("Logan"))
             {
                 images[4] = createImageIcon("Images/" + filename[4]);
                 pic.setIcon(images[4]);
             }

             else if(mname.matches("Annabelle"))
             {
                 images[5] = createImageIcon("Images/" + filename[5]);
                 pic.setIcon(images[5]);
             }

             else if(mname.matches("Dangal"))
             {
                 images[6] = createImageIcon("Images/" + filename[6]);
                 pic.setIcon(images[6]);
             }

             else if(mname.matches("Baahubali"))
             {
                 images[7] = createImageIcon("Images/" + filename[7]);
                 pic.setIcon(images[7]);
             }
              
           }
           System.out.println("Ticket ID PRint:"+tid);
           rs.previous();
           rs.previous();
           if(!(rs.next()))
               JOptionPane.showMessageDialog(null, "INVALID TICKET ID !");
           
           rs.close();
        }catch(SQLException | ClassNotFoundException se){
            //Handle errors for JDBC
            
        }
       //Handle errors for Class.forName
       finally{
           //finally block used to close resources
           try{
              if(stmt!=null)
                 conn.close();
           }catch(SQLException se){
           }// do nothing
           try{
              if(conn!=null)
                 conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }//end finally try
        }//end try
        System.out.println("Goodbye!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmmActionPerformed
        // TODO add your handling code here:
           mainclass.selected_movie = "";
           mainclass.time_booked = "";
           mainclass.final_screen_no = "";
           mainclass.finalTicketCount = "";
           mainclass.custName = "";
           mainclass.custPh = "";
           mainclass.ticketID = "";
           mainclass.date = "";
           mainclass.ticketSeatNo = "";
           mainclass.sid  = 0;
           mainclass.cost = 0;
           mainclass.timeInt = 0;
           mainclass.totAmount = 0;
           mainclass.smsRecvd = "";
           mainclass.smsSend = "";
           mainclass.bookingMode = "";

           new menu().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_btmmActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
         mainclass.selected_movie = "";
         mainclass.time_booked = "";
         mainclass.final_screen_no = "";
         mainclass.finalTicketCount = "";
         mainclass.custName = "";
         mainclass.custPh = "";
         mainclass.ticketID = "";
         mainclass.date = "";
         mainclass.ticketSeatNo = "";
         mainclass.sid  = 0;
         mainclass.cost = 0;
         mainclass.timeInt = 0;
         mainclass.totAmount = 0;
         mainclass.smsRecvd = "";
         mainclass.smsSend = "";
         mainclass.bookingMode = "";

         this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sms_send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sms_send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sms_send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sms_send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sms_send().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexit;
    private javax.swing.JButton btmm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbamt;
    private javax.swing.JLabel lbbid;
    private javax.swing.JLabel lbcost;
    private javax.swing.JLabel lbcustname;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbgst;
    private javax.swing.JLabel lbmoviename;
    private javax.swing.JLabel lbphone;
    private javax.swing.JLabel lbscreen;
    private javax.swing.JLabel lbsno;
    private javax.swing.JLabel lbticketcount;
    private javax.swing.JLabel lbtime;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField txttid;
    // End of variables declaration//GEN-END:variables
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = movie_select.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
                return null;
        }
    }
}
