
import classes.mainclass;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshat
 */
public class time_screen_details extends javax.swing.JFrame {

    /**
     * Creates new form time_screen_details
     */
    public time_screen_details() {
        super("TIME/SCREEN/TICKETS/CUSTOMER DETAILS");
        
        String movie_name= mainclass.selected_movie;
        String time_selected = "";
        mainclass.bookingMode = "COUNTER";
        System.out.println("SELECTED MOVIE NAME="+movie_name);
        initComponents();
        
        rd9am.setVisible(false);
        rd12pm.setVisible(false);
        rd3pm.setVisible(false);
        rd6pm.setVisible(false);
        rd9pm.setVisible(false);
        jButton2.setVisible(false);
        jButton2.setEnabled(false);
        lbnot.setVisible(false);
        cmb.setVisible(false);
        lbcustname.setVisible(false);
        lbcustph.setVisible(false);
        txtcustname.setVisible(false);
        txtcustph.setVisible(false);
        lbsn.setVisible(false);
        lbtime.setVisible(false);
        lbsno.setVisible(false);
        lbt.setVisible(false);
        
        
         // JDBC driver name and database URL
        String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
        String DB_URL = "jdbc:mysql://localhost/movies";

   //  Database credentials
        String USER = "root";
        String PASS = "goodluck";
   
   
   Connection conn = null;
   Statement stmt = null;
   try{
      //STEP 2: Register JDBC driver
      Class.forName("com.mysql.jdbc.Driver");

      //STEP 3: Open a connection
      System.out.println("Connecting to a selected database...");
      conn = DriverManager.getConnection(DB_URL, USER, PASS);
      System.out.println("Connected database successfully...");
      
      //STEP 4: Execute a query
      System.out.println("Creating statement...");
      stmt = conn.createStatement();

      String sql = ("SELECT * FROM screen_movie_map where movie_name='"+movie_name+"'");
            //STEP 5: Extract data from result set
            try (ResultSet rs = stmt.executeQuery(sql)) {
                //STEP 5: Extract data from result set
                while(rs.next()){
                    //Retrieve by column name
                    
                    String getTime = rs.getString("time");
                    String getScreenNo = rs.getString("screen_no");
                   
                    //Display values
                    
                    System.out.println("Time list: " + getTime);
                    System.out.println("Screen No:" + getScreenNo);
                    
                    if(null!=getTime)
                        switch (getTime) {
                        case "09:00 am":
                            rd9am.setVisible(true);
                            time_selected = "09:00 am";
                            break;
                        case "12:00 pm":
                            rd12pm.setVisible(true);
                            time_selected = "12:00 pm";
                            break;
                        case "03:00 pm":
                            rd3pm.setVisible(true);
                            time_selected = "03:00 pm";
                            break;
                        case "06:00 pm":
                            rd6pm.setVisible(true);
                            time_selected = "06:00 pm";
                            break;
                        case "09:00 pm":
                            rd9pm.setVisible(true);
                            time_selected = "09:00 pm";
                            break;
                        default:
                            break;
                    }
                    
         //           lbt.setText(time_selected);
         //           lbsno.setText(getScreenNo);
                        
                }     }
            
            
            
   }catch(SQLException | ClassNotFoundException se){
            //Handle errors for JDBC

   }
        //Handle errors for Class.forName
        finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            conn.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
      }//end finally try
   }//end try
   System.out.println("Goodbye!");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rd9am = new javax.swing.JRadioButton();
        rd12pm = new javax.swing.JRadioButton();
        rd3pm = new javax.swing.JRadioButton();
        rd6pm = new javax.swing.JRadioButton();
        rd9pm = new javax.swing.JRadioButton();
        lbsn = new javax.swing.JLabel();
        lbsno = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        lbt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbnot = new javax.swing.JLabel();
        cmb = new javax.swing.JComboBox<>();
        lbcustname = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        lbcustph = new javax.swing.JLabel();
        txtcustph = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabel2.setText("SELECT TIME:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 157, -1, -1));

        rd9am.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(rd9am);
        rd9am.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        rd9am.setText("09:00 am");
        getContentPane().add(rd9am, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 153, -1, -1));

        rd12pm.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(rd12pm);
        rd12pm.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        rd12pm.setText("12:00 pm");
        getContentPane().add(rd12pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 153, -1, -1));

        rd3pm.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(rd3pm);
        rd3pm.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        rd3pm.setText("03:00 pm");
        getContentPane().add(rd3pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 153, -1, -1));

        rd6pm.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(rd6pm);
        rd6pm.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        rd6pm.setText("06:00 pm");
        getContentPane().add(rd6pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 153, -1, -1));

        rd9pm.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(rd9pm);
        rd9pm.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        rd9pm.setText("09:00 pm");
        getContentPane().add(rd9pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 153, -1, -1));

        lbsn.setBackground(new java.awt.Color(153, 204, 255));
        lbsn.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbsn.setText("SCREEN NO:");
        lbsn.setOpaque(true);
        getContentPane().add(lbsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 335, -1, -1));

        lbsno.setBackground(new java.awt.Color(153, 204, 255));
        lbsno.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbsno.setOpaque(true);
        getContentPane().add(lbsno, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 335, 155, 19));

        lbtime.setBackground(new java.awt.Color(153, 204, 255));
        lbtime.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbtime.setText("TIME:");
        lbtime.setOpaque(true);
        getContentPane().add(lbtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 335, -1, -1));

        lbt.setBackground(new java.awt.Color(153, 204, 255));
        lbt.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbt.setOpaque(true);
        getContentPane().add(lbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 335, 155, 19));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 220, -1, 54));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        jButton2.setText("BOOK SEATS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, 74));

        lbnot.setBackground(new java.awt.Color(153, 204, 255));
        lbnot.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbnot.setText("NUMBER OF TICKETS:");
        lbnot.setOpaque(true);
        getContentPane().add(lbnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 418, -1, -1));

        cmb.setBackground(new java.awt.Color(153, 204, 255));
        cmb.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT---", "1", "2", "3", "4", "5" }));
        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });
        getContentPane().add(cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 415, -1, -1));

        lbcustname.setBackground(new java.awt.Color(153, 204, 255));
        lbcustname.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbcustname.setText("CUSTOMER NAME:");
        lbcustname.setOpaque(true);
        getContentPane().add(lbcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 375, -1, -1));

        txtcustname.setBackground(new java.awt.Color(153, 204, 255));
        txtcustname.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 372, 155, -1));

        lbcustph.setBackground(new java.awt.Color(153, 204, 255));
        lbcustph.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        lbcustph.setText("CUSTOMER PHONE NO:");
        lbcustph.setOpaque(true);
        getContentPane().add(lbcustph, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 375, -1, -1));

        txtcustph.setBackground(new java.awt.Color(153, 204, 255));
        txtcustph.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        getContentPane().add(txtcustph, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 372, 155, -1));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 3, 48)); // NOI18N
        jLabel1.setText("TIME , SCREEN AND NUMBER OF TICKETS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back_lights.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1386, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // JDBC driver name and database URL
    lbnot.setVisible(true);
    cmb.setVisible(true);
    jButton2.setVisible(true);
    lbcustname.setVisible(true);
    lbcustph.setVisible(true);
    txtcustname.setVisible(true);
    txtcustph.setVisible(true);
    lbsn.setVisible(true);
    lbtime.setVisible(true);
    lbt.setVisible(true);
    lbsno.setVisible(true);
    
    if(rd9am.isSelected())
    {
        mainclass.time_booked = "09:00 am";
        mainclass.timeInt = 900;
    } 
    else if(rd12pm.isSelected())
    {
        mainclass.time_booked = "12:00 pm";
        mainclass.timeInt = 1200;
    }
    else if(rd3pm.isSelected())
    {
        mainclass.time_booked = "03:00 pm";
        mainclass.timeInt = 1500;
    }
    else if(rd6pm.isSelected())
    {
        mainclass.time_booked = "06:00 pm";
        mainclass.timeInt = 1800;
    }
    else if(rd9pm.isSelected())
    {
        mainclass.time_booked = "09:00 pm";
        mainclass.timeInt = 2100;
    }
    System.out.println("TIME FROM MAIN CLASS :- "+mainclass.time_booked);
    
    
         
         
    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    String DB_URL = "jdbc:mysql://localhost/movies";

   //  Database credentials
    String USER = "root";
    String PASS = "goodluck";

   
   
   Connection conn = null;
   Statement stmt = null;
   try{
      //STEP 2: Register JDBC driver
      Class.forName("com.mysql.jdbc.Driver");

      //STEP 3: Open a connection
      System.out.println("Connecting to a selected database...");
      conn = DriverManager.getConnection(DB_URL, USER, PASS);
      System.out.println("Connected database successfully...");
      
      //STEP 4: Execute a query
      System.out.println("Creating statement...");
      stmt = conn.createStatement();

      // Extract records without any condition.
      System.out.println("Fetching records without condition...");
      String sql = "SELECT * FROM SCREEN_MOVIE_MAP WHERE MOVIE_NAME ='"+mainclass.selected_movie+"' AND TIME='"+mainclass.time_booked+"'";
        try (ResultSet rs = stmt.executeQuery(sql)) {
            while(rs.next()){
                //Retrieve by column name
                System.out.println("HI Result String");
                String t = rs.getString("time");
                String sno = rs.getString("screen_no");
                //Display values
                System.out.println("TIME WHEN OK BUTTON IS PRESSED : "+t);
                System.out.println("SCREEN NO WHEN OK BUTTON IS PRESSED : "+sno);
                lbt.setText(t);
                lbsno.setText(sno);
                mainclass.final_screen_no = sno;
            } }
   }catch(SQLException | ClassNotFoundException se){
        //Handle errors for JDBC

   }
        //Handle errors for Class.forName
        finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
             conn.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
      }//end finally try
   }//end try
   System.out.println("Goodbye time_screen_details FRAME!");
   
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String value = cmb.getSelectedItem().toString();
        System.out.println(value);
        mainclass.finalTicketCount = value;
        mainclass.custName = txtcustname.getText();
        mainclass.custPh   = txtcustph.getText();
        
        this.dispose();
        new seat_mapping().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(true);
    }//GEN-LAST:event_cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(time_screen_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(time_screen_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(time_screen_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(time_screen_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new time_screen_details().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbcustname;
    private javax.swing.JLabel lbcustph;
    private javax.swing.JLabel lbnot;
    private javax.swing.JLabel lbsn;
    private javax.swing.JLabel lbsno;
    private javax.swing.JLabel lbt;
    private javax.swing.JLabel lbtime;
    private javax.swing.JRadioButton rd12pm;
    private javax.swing.JRadioButton rd3pm;
    private javax.swing.JRadioButton rd6pm;
    private javax.swing.JRadioButton rd9am;
    private javax.swing.JRadioButton rd9pm;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtcustph;
    // End of variables declaration//GEN-END:variables
}
